version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    platform: linux/arm64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    container_name: zookeeper
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERNAL_PORT: 9092
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka-net
    depends_on:
      - zookeeper
    container_name: kafka
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    platform: linux/arm64
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
    ports:
      - "9000:9000"
    networks:
      - kafka-net
    depends_on:
      - kafka
    container_name: kafdrop
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge
