version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    platform: linux/arm64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    volumes:
      - /Users/jsonkar/Fynd/kafka-docker-setup/zookeeper_data/data:/data
      - /Users/jsonkar/Fynd/kafka-docker-setup/zookeeper_data/datalog:/datalog
    networks:
      - kafka-net
    container_name: zookeeper
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094  # Update with correct host
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_INSIDE: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_OUTSIDE: PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"  # Internal port
      - "9093:9093"  # Inside port
      - "9094:9094"  # Outside port
    volumes:
      - /Users/jsonkar/Fynd/kafka-docker-setup/kafka_datadata:/var/lib/kafka/data
    networks:
      - kafka-net
    depends_on:
      - zookeeper
    container_name: kafka
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    platform: linux/arm64
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
    ports:
      - "9000:9000"
    networks:
      - kafka-net
    depends_on:
      - kafka
    container_name: kafdrop
    restart: unless-stopped

networks:
  kafka-net:
    driver: bridge
